# Generated by Django 2.2.5 on 2019-09-04 23:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalIncluido',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('iniciales', models.CharField(max_length=10)),
                ('feceva', models.DateField()),
                ('inclusion', models.CharField(choices=[('1', 'Sí'), ('2', 'No')], max_length=2)),
                ('fecinc', models.DateField(blank=True, null=True)),
                ('numinc', models.IntegerField(blank=True, null=True)),
                ('causano', models.IntegerField()),
                ('investigador', models.CharField(max_length=100)),
                ('firma', models.CharField(choices=[('1', 'Sí'), ('2', 'No')], max_length=2)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical incluido',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
