# Generated by Django 2.2.3 on 2019-09-04 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0002_historicalincluido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalincluido',
            name='history_change_reason',
            field=models.TextField(),
        ),
    ]
