# Generated by Django 2.2.3 on 2019-09-04 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0003_auto_20190904_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalincluido',
            name='history_change_reason',
            field=models.TextField(default='inicial'),
        ),
    ]
