# Generated by Django 2.2.3 on 2019-09-04 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0004_auto_20190904_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalincluido',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
