# Generated by Django 2.2.3 on 2019-10-24 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0005_auto_20190904_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalincluido',
            name='numinc',
        ),
        migrations.RemoveField(
            model_name='incluido',
            name='numinc',
        ),
        migrations.AddField(
            model_name='historicalincluido',
            name='codigo',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='incluido',
            name='codigo',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
