# Generated by Django 2.2.3 on 2019-10-24 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0006_auto_20191024_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalincluido',
            name='causano',
            field=models.IntegerField(verbose_name='Si no incluido refiera número de causa'),
        ),
        migrations.AlterField(
            model_name='historicalincluido',
            name='codigo',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Codigo del sujeto'),
        ),
        migrations.AlterField(
            model_name='historicalincluido',
            name='feceva',
            field=models.DateField(verbose_name='Fecha de evaluación'),
        ),
        migrations.AlterField(
            model_name='historicalincluido',
            name='fecinc',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Inclusión'),
        ),
        migrations.AlterField(
            model_name='historicalincluido',
            name='firma',
            field=models.CharField(choices=[('1', 'Sí'), ('2', 'No')], max_length=2, verbose_name='Firma'),
        ),
        migrations.AlterField(
            model_name='historicalincluido',
            name='inclusion',
            field=models.CharField(choices=[('1', 'Sí'), ('2', 'No')], max_length=2, verbose_name='¿El sujeto se incluyo?'),
        ),
        migrations.AlterField(
            model_name='historicalincluido',
            name='iniciales',
            field=models.CharField(max_length=10, verbose_name='Iniciales del sujeto'),
        ),
        migrations.AlterField(
            model_name='historicalincluido',
            name='investigador',
            field=models.CharField(max_length=100, verbose_name='Investigador'),
        ),
        migrations.AlterField(
            model_name='historicalincluido',
            name='numero',
            field=models.IntegerField(verbose_name='No.'),
        ),
        migrations.AlterField(
            model_name='incluido',
            name='causano',
            field=models.IntegerField(verbose_name='Si no incluido refiera número de causa'),
        ),
        migrations.AlterField(
            model_name='incluido',
            name='codigo',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Codigo del sujeto'),
        ),
        migrations.AlterField(
            model_name='incluido',
            name='feceva',
            field=models.DateField(verbose_name='Fecha de evaluación'),
        ),
        migrations.AlterField(
            model_name='incluido',
            name='fecinc',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Inclusión'),
        ),
        migrations.AlterField(
            model_name='incluido',
            name='firma',
            field=models.CharField(choices=[('1', 'Sí'), ('2', 'No')], max_length=2, verbose_name='Firma'),
        ),
        migrations.AlterField(
            model_name='incluido',
            name='inclusion',
            field=models.CharField(choices=[('1', 'Sí'), ('2', 'No')], max_length=2, verbose_name='¿El sujeto se incluyo?'),
        ),
        migrations.AlterField(
            model_name='incluido',
            name='iniciales',
            field=models.CharField(max_length=10, verbose_name='Iniciales del sujeto'),
        ),
        migrations.AlterField(
            model_name='incluido',
            name='investigador',
            field=models.CharField(max_length=100, verbose_name='Investigador'),
        ),
        migrations.AlterField(
            model_name='incluido',
            name='numero',
            field=models.IntegerField(verbose_name='No.'),
        ),
    ]
