# Generated by Django 2.2.3 on 2019-10-25 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registros', '0007_auto_20191024_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecDevPi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('cantidad_1', models.IntegerField(verbose_name='Cantidad de bolsas individuales')),
                ('codigo_1', models.TextField(verbose_name='Código de las bolsas')),
                ('entrega_1', models.CharField(max_length=100, verbose_name='Entrega')),
                ('recibe_1', models.CharField(max_length=100, verbose_name='Recibe')),
                ('cantidad_2', models.IntegerField(verbose_name='Cantidad de bolsas individuales utilizadas')),
                ('cantidad_3', models.IntegerField(verbose_name='Cantidad de bolsas individuales sin utilizar')),
                ('codigo_2', models.TextField(verbose_name='Código de las bolsas sin utilizar')),
                ('entrega_2', models.CharField(max_length=100, verbose_name='Entrega')),
                ('recibe_2', models.CharField(max_length=100, verbose_name='Recibe')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalRecDevPi',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('cantidad_1', models.IntegerField(verbose_name='Cantidad de bolsas individuales')),
                ('codigo_1', models.TextField(verbose_name='Código de las bolsas')),
                ('entrega_1', models.CharField(max_length=100, verbose_name='Entrega')),
                ('recibe_1', models.CharField(max_length=100, verbose_name='Recibe')),
                ('cantidad_2', models.IntegerField(verbose_name='Cantidad de bolsas individuales utilizadas')),
                ('cantidad_3', models.IntegerField(verbose_name='Cantidad de bolsas individuales sin utilizar')),
                ('codigo_2', models.TextField(verbose_name='Código de las bolsas sin utilizar')),
                ('entrega_2', models.CharField(max_length=100, verbose_name='Entrega')),
                ('recibe_2', models.CharField(max_length=100, verbose_name='Recibe')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical rec dev pi',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
