# Generated by Django 2.2.3 on 2019-11-05 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0008_historicalrecdevpi_recdevpi'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalincluido',
            name='municipio',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='historicalincluido',
            name='provincia',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='historicalincluido',
            name='sclinico',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='incluido',
            name='municipio',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='incluido',
            name='provincia',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='incluido',
            name='sclinico',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
