# Generated by Django 2.2.3 on 2019-11-06 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0009_auto_20191105_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalincluido',
            name='municipio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalincluido',
            name='provincia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalincluido',
            name='sclinico',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incluido',
            name='municipio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incluido',
            name='provincia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incluido',
            name='sclinico',
            field=models.TextField(blank=True, null=True),
        ),
    ]
