# Generated by Django 2.2.3 on 2019-11-18 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0010_auto_20191106_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrecdevpi',
            name='municipio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalrecdevpi',
            name='provincia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalrecdevpi',
            name='sclinico',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recdevpi',
            name='municipio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recdevpi',
            name='provincia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recdevpi',
            name='sclinico',
            field=models.TextField(blank=True, null=True),
        ),
    ]
