# Generated by Django 2.2.3 on 2019-11-18 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registros', '0011_auto_20191118_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interrupcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provincia', models.TextField(blank=True, null=True)),
                ('municipio', models.TextField(blank=True, null=True)),
                ('sclinico', models.TextField(blank=True, null=True)),
                ('numero', models.IntegerField(verbose_name='No.')),
                ('codigo', models.CharField(max_length=11, verbose_name='Codigo de identificación del sujeto')),
                ('fecint', models.DateField(verbose_name='Fecha de evaluación')),
                ('criterioi', models.IntegerField(verbose_name='Criterios de interrupción')),
                ('investigador', models.CharField(max_length=100, verbose_name='Investigador')),
                ('firma', models.CharField(choices=[('1', 'Sí'), ('2', 'No')], max_length=2, verbose_name='Firma')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalInterrupcion',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('provincia', models.TextField(blank=True, null=True)),
                ('municipio', models.TextField(blank=True, null=True)),
                ('sclinico', models.TextField(blank=True, null=True)),
                ('numero', models.IntegerField(verbose_name='No.')),
                ('codigo', models.CharField(max_length=11, verbose_name='Codigo de identificación del sujeto')),
                ('fecint', models.DateField(verbose_name='Fecha de evaluación')),
                ('criterioi', models.IntegerField(verbose_name='Criterios de interrupción')),
                ('investigador', models.CharField(max_length=100, verbose_name='Investigador')),
                ('firma', models.CharField(choices=[('1', 'Sí'), ('2', 'No')], max_length=2, verbose_name='Firma')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical interrupcion',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
