# Generated by Django 2.2.3 on 2019-11-04 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_historicalperfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalperfil',
            name='municipio',
            field=models.TextField(blank=True, choices=[('SA', 'Santa Clara'), ('CA', 'Camajuaní'), ('RE', 'Remedios'), ('CI', 'Caibarien'), ('SC', 'Santiago de Cuba')], null=True),
        ),
        migrations.AddField(
            model_name='historicalperfil',
            name='provincia',
            field=models.TextField(blank=True, choices=[('LH', 'La Habana'), ('CIE', 'Cienfuegos'), ('VC', 'Villa Clara'), ('SC', 'Santiago de cuba')], null=True),
        ),
        migrations.AddField(
            model_name='historicalperfil',
            name='sclinico',
            field=models.TextField(blank=True, choices=[('IN', 'Infanti Norte'), ('IS', 'Infantil Sur'), ('CJ', 'Pol. Carlos J Finlay'), ('CT', 'Pol. Camilo Torres'), ('LP', 'Pol. López Peña'), ('28', 'Pol. 28 de Septiembre'), ('30', 'Pol 30 de Noviembre'), ('JJ', 'Pol. José Martí'), ('JP', 'Pol. Josué País'), ('LS', 'CPHEM SC'), ('ES', 'EMCOMED Santiago de Cuba'), ('LO', 'Laboratorio Oriente'), ('LF', 'Lab. Inmunología Clínica IFV'), ('JL', 'HPP José Luis Miranda'), ('SA', 'Pol. Santa Clara'), ('JR', 'Pol. José Ramón Acosta'), ('MA', 'Pol. Marta Abreu'), ('XX', 'Pol XX Aniversario'), ('CR', 'Pol Capitán Roberto Fleites'), ('CH', 'Pol. Chiqui Gómez Lubián'), ('LV', 'CPHEM VC'), ('EV', 'EMCOMED Villa Clara'), ('OC', 'Pol. Octavio de la Concepción y Pedraja'), ('MF', 'Pol. Manuel Fajardo Rivero'), ('HM', 'HMGD 26 de Diciembre'), ('XA', 'Pol. XXX Aniversario'), ('CC', 'Pol. Camilo Cienfuegos'), ('LF', 'Pol. Leandro Figueroa'), ('PA', 'Pol. Pablo Aguero')], null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='municipio',
            field=models.TextField(blank=True, choices=[('SA', 'Santa Clara'), ('CA', 'Camajuaní'), ('RE', 'Remedios'), ('CI', 'Caibarien'), ('SC', 'Santiago de Cuba')], null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='provincia',
            field=models.TextField(blank=True, choices=[('LH', 'La Habana'), ('CIE', 'Cienfuegos'), ('VC', 'Villa Clara'), ('SC', 'Santiago de cuba')], null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='sclinico',
            field=models.TextField(blank=True, choices=[('IN', 'Infanti Norte'), ('IS', 'Infantil Sur'), ('CJ', 'Pol. Carlos J Finlay'), ('CT', 'Pol. Camilo Torres'), ('LP', 'Pol. López Peña'), ('28', 'Pol. 28 de Septiembre'), ('30', 'Pol 30 de Noviembre'), ('JJ', 'Pol. José Martí'), ('JP', 'Pol. Josué País'), ('LS', 'CPHEM SC'), ('ES', 'EMCOMED Santiago de Cuba'), ('LO', 'Laboratorio Oriente'), ('LF', 'Lab. Inmunología Clínica IFV'), ('JL', 'HPP José Luis Miranda'), ('SA', 'Pol. Santa Clara'), ('JR', 'Pol. José Ramón Acosta'), ('MA', 'Pol. Marta Abreu'), ('XX', 'Pol XX Aniversario'), ('CR', 'Pol Capitán Roberto Fleites'), ('CH', 'Pol. Chiqui Gómez Lubián'), ('LV', 'CPHEM VC'), ('EV', 'EMCOMED Villa Clara'), ('OC', 'Pol. Octavio de la Concepción y Pedraja'), ('MF', 'Pol. Manuel Fajardo Rivero'), ('HM', 'HMGD 26 de Diciembre'), ('XA', 'Pol. XXX Aniversario'), ('CC', 'Pol. Camilo Cienfuegos'), ('LF', 'Pol. Leandro Figueroa'), ('PA', 'Pol. Pablo Aguero')], null=True),
        ),
    ]
